### ISSUE TITLE
Copying album title results in "Cannot read properties of undefined (reading 'operation')"

### ISSUE THREAD

**Issue by f1at1ander** [pnthach95/spicetify-extensions#21]
Spotify for macOS (Apple Silicon)
1.2.40.599.g606b7f29
Spicetify v2.36.13
xpui_2024-06-17_1718636116813_606b7f2
cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Runtime: Chrome
Build System: CMake

Starting with Spicetify  v2.36.12, right-clicking on an album title and choosing Copy Text gives me a popup that says "Error: Cannot read properties of undefined (reading 'operation')"

The console log is below. No new API call appears in the Network tab.

```
copytoclipboard.js?time=1719280848830:1

TypeError: Cannot read properties of undefined (reading 'operation')
    at xpui.js:1:3124384
    at h (vendor~xpui.js:1:3313483)
    at Generator.<anonymous> (vendor~xpui.js:1:3314825)
    at Generator.next (vendor~xpui.js:1:3313912)
    at r (vendor~xpui.js:1:3494536)
    at s (vendor~xpui.js:1:3494739)
    at vendor~xpui.js:1:3494798
    at new Promise (<anonymous>)
    at Object.<anonymous> (vendor~xpui.js:1:3494679)
    at Object.<anonymous> (xpui.js:1:3124628)
```

**Comment by pnthach95** [comment]
Hotfix is uploaded
